name: 'The Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: 'CI'
    uses: vinayakkulkarni/v-kong-dashboard/.github/workflows/ci.yml@main
  automerger:
    name: 'Automerge Dependabot PRs'
    needs:
      - ci
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: vinayakkulkarni/v-kong-dashboard/.github/workflows/automerger.yml@main
  builder:
    name: 'Builder'
    needs:
      - ci
    if: ${{ github.event_name == 'push' }}
    uses: vinayakkulkarni/v-kong-dashboard/.github/workflows/builder.yml@main
    with:
      branch: ${{ needs.extract-branch.outputs.current_branch }}
